### PR TITLE
[issue 572]: fix log format

### LINKED ISSUE #572: format error
https://github.com/Qihoo360/wayne/blob/620d4a025020e8d17e41a36b7f717d74b0aa1829/src/backend/controllers/permission/user.go#L81

params未实现String方法

### PR DESCRIPTION
**Pull request by cugxuan**
Fixes #572 

fix the log format

because the type `QueryParam` don't have the function `String()`
```go
logs.Error("get total count by param (%s) error. %v", param, err)
// should convert to this
logs.Error("get total count by param (%v) error. %v", param, err)
```

### CODE REVIEW

File: src/backend/controllers/apikey/apikey.go [hunk 1]
```diff
@@ -80,14 +80,14 @@ func (c *ApiKeyController) List() {
 	param.Relate = "Group"
 	total, err := models.GetTotal(new(models.APIKey), param)
 	if err != nil {
-		logs.Error("get total count by param (%s) error. %v", param, err)
+		logs.Error("get total count by param (%v) error. %v", param, err)
```
Comment (zhangguanzhang) [inline src/backend/controllers/apikey/apikey.go:83]: good
